Se preuba la api de Sonar

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -41,25 +41,27 @@ jobs:
           -Dsonar.branch.name=${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
           -Dsonar.verbose=true
       continue-on-error: false
+    
+    - name: Chequeo SonarCloud Quality Gate
+      run: |
+        RESPONSE=$(curl -s -u "${{ secrets.SONARCLOUD_TOKEN }}:" \
+        "https://sonarcloud.io/api/qualitygates/project_status?projectKey=obligatorio-devops-corbalan-arzuaga:Obligatorio-DevOps-Corbalan-Arzuaga_FE-react")
+    
+        echo "Respuesta de la API: $RESPONSE"
+    
+        STATUS=$(echo "$RESPONSE" | jq -r '.projectStatus.status')
+    
+        if [ "$STATUS" != "OK" ]; then
+          echo "Quality Gate failed: $STATUS"
+          exit 1
+        else
+          echo "Quality Gate passed: $STATUS"
+        fi
+      env:
+        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
 
-- name: Chequeo SonarCloud Quality Gate
-  run: |
-    RESPONSE=$(curl -s -u "${{ secrets.SONARCLOUD_TOKEN }}:" \
-    "https://sonarcloud.io/api/qualitygates/project_status?projectKey=obligatorio-devops-corbalan-arzuaga:Obligatorio-DevOps-Corbalan-Arzuaga_FE-react")
-    
-    echo "Respuesta de la API: $RESPONSE"
-    
-    STATUS=$(echo "$RESPONSE" | jq -r '.projectStatus.status')
-    
-    if [ "$STATUS" != "OK" ]; then
-      echo "Quality Gate failed: $STATUS"
-      exit 1
-    else
-      echo "Quality Gate passed: $STATUS"
-    fi
-  env:
-    SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
 
+    
     - name: Build project
       run: npm run build -- --project=catalog --configuration=production
 
